# Generated by Django 5.2.1 on 2025-06-08 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_account_type_alter_account_balance'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trasaction',
            new_name='Transaction',
        ),
    ]
