# Generated by Django 5.2.1 on 2025-06-13 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_rename_trasaction_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_occurred',
            field=models.DateField(default=datetime.datetime(2025, 6, 13, 19, 28, 35, 586745, tzinfo=datetime.timezone.utc)),
        ),
    ]
