# Generated by Django 5.2.1 on 2025-06-13 19:40

import transactions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_date_occurred'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_occurred',
            field=models.DateField(default=transactions.models.tz_aware_date),
        ),
    ]
